# Generated by Django 5.1.15 on 2026-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisioning', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='task_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
