# Generated by Django 5.1.15 on 2026-05-29 17:43

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        # Enable pgvector before creating the table that uses vector(1024).
        # Owned here (not in tenants) so the dependency edge is explicit.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name='RuleChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_identifier', models.CharField(db_index=True, help_text='Denormalized copy of ticket_type.identifier — kept for backward-compat queries.', max_length=100)),
                ('rule_id', models.CharField(db_index=True, max_length=120)),
                ('source_path', models.CharField(blank=True, help_text='Origin marker — set if imported from a file, blank if created via UI.', max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('decision_hint', models.CharField(blank=True, max_length=30)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('post_actions', models.JSONField(default=list)),
                ('extra', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_chunks', to='tenants.org')),
                ('ticket_type', models.ForeignKey(blank=True, help_text='Nullable for migration safety. New rules created via the admin UI always set this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tickets.tickettype')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'plugin_identifier'], name='kb_rulechun_org_id_eee627_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'plugin_identifier', 'rule_id'), name='uniq_org_plugin_rule')],
            },
        ),
    ]
