# Generated by Django 5.1.15 on 2026-05-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_team_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['team', 'user__email']},
        ),
    ]
