# Generated by Django 5.1.15 on 2026-05-29 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('decided', 'Decided (auto)'), ('approved', 'Approved (human)'), ('rejected', 'Rejected (human)'), ('closed', 'Closed')], default='open', max_length=20)),
                ('decision_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenants.org')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='tenants.org')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['ticket', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequential', models.BooleanField(default=True, help_text='If true, stages must be decided in order. If false, any stage can decide in parallel.')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('require_citation', models.BooleanField(default=True)),
                ('shadow_mode', models.BooleanField(default=True, help_text='When true, decisions are logged but not applied to the ticket. Flip off once eval precision is ≥98%.')),
                ('system_prompt', models.TextField(blank=True, help_text='The prompt prepended to every decisioning call for this ticket type. Edited in the UI — no file paths.')),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tenants.org')),
            ],
            options={
                'ordering': ['org', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='TicketTypeField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('bool', 'Boolean'), ('text', 'Long text'), ('enum', 'Enum (dropdown)')], default='string', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Only for enum fields.')),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.tickettype')),
            ],
            options={
                'ordering': ['ticket_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('approvers', models.JSONField(blank=True, default=list, help_text="Role or group identifiers (strings). v0 doesn't promote these to a Team table — see WorkflowStage for the typed extension point.")),
                ('mode', models.CharField(choices=[('any_member', 'Any member'), ('unanimous_team', 'Unanimous team'), ('majority', 'Majority'), ('specific_user', 'Specific user')], default='any_member', max_length=30)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='tickets.tickettype')),
            ],
            options={
                'ordering': ['ticket_type', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['org', 'status', '-created_at'], name='tickets_tic_org_id_b7db83_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['org', 'ticket_type', '-created_at'], name='tickets_tic_org_id_55e327_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstage',
            constraint=models.UniqueConstraint(fields=('ticket', 'order'), name='uniq_ticket_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('org', 'identifier'), name='uniq_org_ticket_type'),
        ),
        migrations.AddConstraint(
            model_name='tickettypefield',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'name'), name='uniq_tt_field_name'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'order'), name='uniq_tt_stage_order'),
        ),
    ]
