# Generated by Django 5.1.15 on 2026-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstage',
            name='approvers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
