# Generated by Django 5.1.15 on 2026-05-30 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_approvalstage_approvers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tickets.approvalstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', 'decided_at'],
                'indexes': [models.Index(fields=['stage', 'decision'], name='tickets_sta_stage_i_81dd8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('stage', 'user'), name='uniq_stage_voter')],
            },
        ),
    ]
