# Generated by Django 5.1.15 on 2026-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_stagevote_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettypefield',
            name='choices_if',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tickettypefield',
            name='show_if',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettypefield',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='Default choices for enum fields. Overridden by the first matching choices_if rule.'),
        ),
    ]
